"""Render a scan result as a self-contained HTML page.

Everything (styles included) is inlined so the file works offline and can be
committed or published to GitHub Pages with no assets to host.
"""

from __future__ import annotations

from html import escape

from depwatch.core.models import ScanResult, ScoredPackage
from depwatch.report.summary import (
    any_fix,
    dominant_driver,
    fix_hint,
    high_risk_count,
    key_finding,
    select_risky,
)
from depwatch.scoring.bands import RiskBand, classify

_BAND_CLASS: dict[RiskBand, str] = {
    RiskBand.LOW: "low",
    RiskBand.MODERATE: "moderate",
    RiskBand.HIGH: "high",
    RiskBand.CRITICAL: "critical",
}

_CSS = """
:root { color-scheme: light dark; }
body { font: 16px/1.5 -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
       max-width: 880px; margin: 2.5rem auto; padding: 0 1rem; color: #1b1f24; }
h1 { margin-bottom: 0.2rem; }
.sub { color: #57606a; margin-top: 0; }
.headline { background: #f6f8fa; border: 1px solid #d0d7de; border-radius: 8px;
            padding: 0.8rem 1rem; margin: 1.2rem 0; }
table { border-collapse: collapse; width: 100%; }
th, td { text-align: left; padding: 0.55rem 0.7rem; border-bottom: 1px solid #d8dee4; }
th { font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.03em; color: #57606a; }
.badge { display: inline-block; padding: 0.1rem 0.5rem; border-radius: 999px;
         font-size: 0.78rem; font-weight: 600; color: #fff; }
.badge.low { background: #1a7f37; }
.badge.moderate { background: #9a6700; }
.badge.high { background: #cf222e; }
.badge.critical { background: #82071e; }
.muted { color: #57606a; }
.fix { color: #0969da; white-space: nowrap; }
footer { margin-top: 1.5rem; color: #8b949e; font-size: 0.85rem; }
"""


def scan_to_html(result: ScanResult, *, limit: int = 10) -> str:
    """The scan as one self-contained HTML document."""
    return _document(_body(result, limit))


def _body(result: ScanResult, limit: int) -> str:
    when = result.created_at.strftime("%Y-%m-%d %H:%M UTC")
    parts = [
        "<h1>depwatch</h1>",
        f'<p class="sub">Dependency risk report · {escape(when)}</p>',
    ]
    if not result.packages:
        parts.append("<p>No packages to scan.</p>")
        return "\n".join(parts)

    total = len(result.packages)
    driver = dominant_driver(result.packages)
    headline = (
        f"Scanned <strong>{total}</strong> package(s) from "
        f"<code>{escape(result.source)}</code> — "
        f"<strong>{high_risk_count(result.packages)}</strong> high-risk"
    )
    if driver:
        headline += f" · top risk driver: <strong>{escape(driver)}</strong>"
    parts.append(f'<div class="headline">{headline}</div>')

    risky = select_risky(result.packages)
    if not risky:
        parts.append(f"<p>All <strong>{total}</strong> packages look low-risk. ✅</p>")
        return "\n".join(parts)

    parts.append(_table(risky[:limit]))
    if len(risky) > limit:
        parts.append(f'<p class="muted">… and {len(risky) - limit} more risky package(s).</p>')
    low = total - len(risky)
    if low:
        parts.append(f'<p class="muted">{low} package(s) look low-risk.</p>')
    return "\n".join(parts)


def _table(packages: list[ScoredPackage]) -> str:
    show_fix = any_fix(packages)
    header = (
        "<tr><th>#</th><th>Package</th><th>Version</th><th>Type</th>"
        "<th>Risk</th><th>Key finding</th>"
    )
    header += "<th>Fix</th></tr>" if show_fix else "</tr>"
    rows = ["<table>", header]
    for rank, package in enumerate(packages, start=1):
        band = classify(package.risk.overall)
        kind = "direct" if package.signals.is_direct else "transitive"
        cells = (
            f"<tr><td>{rank}</td>"
            f"<td><strong>{escape(package.signals.name)}</strong></td>"
            f"<td>{escape(package.signals.version)}</td>"
            f"<td>{kind}</td>"
            f'<td><span class="badge {_BAND_CLASS[band]}">{band.value.upper()}</span> '
            f"{package.risk.overall:.2f}</td>"
            f"<td>{escape(key_finding(package))}</td>"
        )
        if show_fix:
            cells += f'<td class="fix">{escape(fix_hint(package) or "—")}</td>'
        rows.append(cells + "</tr>")
    rows.append("</table>")
    return "\n".join(rows)


def _document(body: str) -> str:
    return (
        "<!doctype html>\n"
        '<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "<title>depwatch — dependency risk</title>\n"
        f"<style>{_CSS}</style>\n</head>\n<body>\n"
        f"{body}\n"
        '<footer>Generated by depwatch · <a href="https://github.com/Tim-tran1406/depwatch">'
        "github.com/Tim-tran1406/depwatch</a></footer>\n"
        "</body>\n</html>\n"
    )
